# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy 1
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - pruebaSmartBiterp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore CashFlowPortal.Web/CashFlowPortal.Web.csproj

      - name: Build
        run: dotnet build CashFlowPortal.Web/CashFlowPortal.Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish CashFlowPortal.Web/CashFlowPortal.Web.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pruebaSmartBiterp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_34B05A0D9B69497FBF8EBA752473839E }}
          package: ./publish
